### PR TITLE
Added page break

### PR DESCRIPTION
**Pull request by sqdge**
I added the ability to start on a new page. I'm not sure if the new code is in the right place.

### CODE REVIEW

**Comment by dolanmiu** [comment]
hi, ill check it out in the evening.

thanks for your interest!

What do you think about the name of this library? Shall I re-name it something more appropriate?

**Comment by sqdge** [comment]
Office-Clippy was the only NodeJS module I could find that did the headings in a simple way. I think the module is great – very simple to use, had no problems creating a word document (I haven’t checked it with other formats). I just needed the full page break option to help separate out some content.

Office-clippy is a bit of a strange name, since it doesn’t use Clippy at all. However, it made me laugh and look at the project. Officegen is the top google search for this tool, but it doesn’t do headings 1-6. You could go with something like office-maker, but that’s not as funny!

I’ll be testing the module today to automatically build a 100+ page document.

Also, my pull request failed the TravisCI test… not really sure why.

-BenG

**Comment by dolanmiu** [comment]
Ok, I'll keep it Office-Clippy for now. I used to love the Clippy assistant when I was a kid when I had Windows 98. R.I.P Clippy. Someone should make a plugin which revives him for Word 2015

I do not use TravisCI (I don't know how to use it)

You have almost got the right idea, but it should be in a different file. 
I try to keep everything modular to its easy to understand. You put it in border.js (but page breaks arent related to borders). I have a file called alignment.js which handles all alignment related stuff for example.

After the file is made, you link the method into the index.js, so it avoids polluting the index. I HATE developers which shove everything in one massive file. It going to give me RSI from scrolling the god damn 5000 line file.

**Comment by dolanmiu** [comment]
I have merged this, and will correct it.

If you can improve this further, feel free. I want to add style support one day.

**Comment by sqdge** [comment]
Yeah, I knew that borders.js was the wrong file. I only put it in there because of the thematicBreak (they both have “break” in their name!)

I also liked clippy. Although, I preferred changing him to the wizard or the ball… I was young, wizards were cool.

This is my first ever github merge!

Any idea how npm updates to code changes?

-BenG

**Comment by dolanmiu** [comment]
Ok, I moved the code to break.js.

You got the general idea, it would've worked, but I am quite OCD with cleanliness.

I wasn't too fond of the wizard, the ball was my second favorite, I remember right clicking the assistants and playing a random animation, haha it was so random, but so fun

Have you tested that it works? my change shouldn't break anything, but in case it does, let me know, and I'll create a hot-fix LOL.

What do you mean npm updates to code changes? Do you mean how it releases a new version? I just have to tag it, and type ```npm publish ./```

**Comment by dolanmiu** [comment]
Congrats on your first merge! This is the second time someone wanted to contribute to one of my projects. Best feeling ever

**Comment by sqdge** [comment]
I think “npm publish” was what I was wondering about. Basically, wondering how it knows there is new code when I got to “npm install office-clippy”.

-BenG

**Comment by dolanmiu** [comment]
Ok, version 0.0.7 has been released! Hopefully it works out ok

**Pull request merged**
